### ISSUE TITLE
ENV

### ISSUE THREAD

**Issue by rossman22590** [henrycunh/geppeto#16]
can i use OPENAI_API_KEY in env as key?

**Comment by henrycunh** [comment]
I'll implement support for this!

Just for a better understanding of this use case: You want to have a single API Key for a self-hosted version, shared by anyone that uses this instance, right?

Having the application protected by password would also be necessary?

**Comment by rossman22590** [comment]
yes and yes

**Comment by henrycunh** [comment]
Hey @rossman22590, just letting you know the feature is ready to go :]

You can set the API Key through the `OPENAI_API_KEY` environment variable, and a password through the `GEPPETO_PASSWORD` one.

**Comment by rossman22590** [comment]
it works! this is great. can we hide the key in the ui in fornt end maybe ************************
