### ISSUE TITLE
Corner case: Geppeto can't handle multiple conversations in the same session.

### ISSUE THREAD

**Issue by gdassori** [henrycunh/geppeto#24]
Switching between chat tabs during a response causes unwanted behavior\glitches.

How to reproduce: Start a chat and request a long response of some kind, then during the response switch to a "new chat" and send a message.

**Comment by gdassori** [comment]
I don't know if Geppeto should be able to handle multiple responses at the same time and go beyond the ChatGPT UI\UX, since OpenAI API would permit this.

**Comment by henrycunh** [comment]
Oh yeah, we should definitely allow it! Thanks for catching it ❤️

**Comment by rossman22590** [comment]
is this fixed?

**Comment by henrycunh** [comment]
It is now :]
