### ISSUE TITLE
local storage of chat history

### ISSUE THREAD

**Issue by wwwCielwww** [henrycunh/geppeto#35]
Hello, thanks for the great repo!

When I use `npm run dev` to run the app locally, I believe each conversation is stored to some place because I can see my conversation history with chatgpt. 

I am quite new to vue.js. I could not find the relevant code or files on my own. I'd really appreciate someone to tell me where the list of conversations is stored. Thanks a lot!

**Comment by henrycunh** [comment]
Hey!

The conversation data is stored in a IndexedDB store. The file with the definition for the stores and some of its setup code is in [`~/composables/idb.ts`](https://github.com/henrycunh/geppeto/blob/main/composables/idb.ts).

IDB and [Dexie](https://dexie.org/) makes interacting with locally stored data really easy and maintainable!

**Comment by wwwCielwww** [comment]
Thanks a lot!!
