### ISSUE TITLE
Bug report: GPT-4 model hangs if API does not support it

### ISSUE THREAD

**Issue by gdassori** [henrycunh/geppeto#8]
![image](https://user-images.githubusercontent.com/5659270/229298523-bce91edb-12df-4a76-b5eb-cf6a2cd3e969.png)

No error is reported at all.

**Comment by henrycunh** [comment]
Habemus error messages!
![image](https://user-images.githubusercontent.com/8951736/229323546-fbb2f989-379d-436d-9dce-db92c10b0a59.png)

**Comment by henrycunh** [comment]
Closed by #14
